apiVersion: apps/v1
kind: Deployment
metadata:
  name: draft-app
spec:
  replicas: 9
  selector:
    matchLabels:
      app: draft-app
  template:
    metadata:
      labels:
        app: draft-app
    spec:
      containers:
        - name: draft-app
          image: draft-raft
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: draft-app-service
  labels:
    app: draft-app
spec:
  clusterIP: None # This setting makes the service "headless"
  selector:
    app: draft-app
  ports:
    - protocol: TCP
      port: 3000
